# Generated by Django 4.0.6 on 2024-04-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('customer_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResilianceCustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=50, null=True)),
                ('question_2', models.CharField(max_length=50, null=True)),
                ('question_3', models.CharField(max_length=50, null=True)),
                ('question_4', models.CharField(max_length=50, null=True)),
                ('question_5', models.CharField(max_length=50, null=True)),
                ('question_6', models.CharField(max_length=50, null=True)),
                ('question_7', models.CharField(max_length=50, null=True)),
                ('question_8', models.CharField(max_length=50, null=True)),
                ('question_9', models.CharField(max_length=50, null=True)),
                ('question_10', models.CharField(max_length=50, null=True)),
                ('question_11', models.CharField(max_length=50, null=True)),
                ('question_12', models.CharField(max_length=50, null=True)),
                ('question_13', models.CharField(max_length=50, null=True)),
                ('question_14', models.CharField(max_length=50, null=True)),
                ('question_15', models.CharField(max_length=50, null=True)),
                ('question_16', models.CharField(max_length=50, null=True)),
                ('question_17', models.CharField(max_length=50, null=True)),
                ('question_18', models.CharField(max_length=50, null=True)),
                ('question_19', models.CharField(max_length=50, null=True)),
                ('question_20', models.CharField(max_length=50, null=True)),
                ('question_21', models.CharField(max_length=50, null=True)),
                ('building_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DRF_App.buildingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=50, null=True)),
                ('question_2', models.CharField(max_length=50, null=True)),
                ('question_3', models.CharField(max_length=50, null=True)),
                ('question_4', models.CharField(max_length=50, null=True)),
                ('question_5', models.CharField(max_length=50, null=True)),
                ('question_6', models.CharField(max_length=50, null=True)),
                ('question_7', models.CharField(max_length=50, null=True)),
                ('question_8', models.CharField(max_length=50, null=True)),
                ('question_9', models.CharField(max_length=50, null=True)),
                ('building_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DRF_App.buildingaddress')),
            ],
        ),
    ]
