# Generated by Django 4.0.6 on 2024-04-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App', '0002_buildingaddress_resiliancecustomerdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
